### ISSUE TITLE
Update documentation please

### ISSUE THREAD

**Issue by oreHGA** [docusign/docusign-node-client#78] opened 2018-01-19 04:02 UTC
Hi, great work with the node client. I think it'll be alot easier for people unfamiliar w the codebase if the code samples/readme reflect the recent changes being made to the node client itself. 

Example : The getter and setters are scrapped from the node client but the github repo still has examples using those getter and setters that no longer work anymore.

Apart from that, its a nice client :100:

**Comment by mmallis87** [comment] 2018-01-19 23:23
@oreHGA thank you for reporting this and for the kind words. We are aware that our SDK docs are something not up to date. I will keep this open until we update the code samples.

**Comment by mmallis87** [comment] 2018-01-22 00:59
potential dupe of #72

**Closed** 2018-02-13 17:01 UTC
