### ISSUE TITLE
Webhook not hitting application URL

### ISSUE THREAD

**Issue by ashutosh8** [docusign/docusign-node-client#125] opened 2019-01-17 15:39 UTC
We are tying to implement webhook for envelope status with our Node application but the webhook does not hit our API endpoint, We tried the following code as shown in [https://developers.docusign.com/esign-rest-api/code-examples/webhook-status](url)

````
                    envDef.eventNotification = {
                        "url": webhookUrl,
                        "loggingEnabled": "true",
                        "requireAcknowledgment": "true",
                        "useSoapInterface": "false",
                        "includeCertificateWithSoap": "false",
                        "signMessageWithX509Cert": "false",
                        "includeDocuments": "true",
                        "includeEnvelopeVoidReason": "true",
                        "includeTimeZone": "true",
                        "includeSenderAccountAsCustomField": "true",
                        "includeDocumentFields": "true",
                        "includeCertificateOfCompletion": "true",
                        "envelopeEvents": [
                            { "envelopeEventStatusCode": "sent" },
                            { "envelopeEventStatusCode": "delivered" },
                            { "envelopeEventStatusCode": "completed" },
                            { "envelopeEventStatusCode": "declined" },
                            { "envelopeEventStatusCode": "voided" }
                        ], 
                        "recipientEvents": [
                            {"recipientEventStatusCode": "Sent" },
                            { "recipientEventStatusCode": "Delivered" },
                            { "recipientEventStatusCode": "Completed" },
                            { "recipientEventStatusCode": "Declined" },
                            { "recipientEventStatusCode": "AuthenticationFailed" },
                            { "recipientEventStatusCode": "AutoResponded" }
                        ]
                    }
````

We also tried to implement this using the node webhook recipe as shown in [https://github.com/docusign/recipe-010-webhook-node/](url)

````
var envelopeEvents = [];
var envelopeEvent = new docusign.EnvelopeEvent();
envelopeEvent.setEnvelopeEventStatusCode("sent");`
````

The code throws _setEnvelopeEventStatusCode is not a function_ error in docusign node module version 4.2.1 .

Seems like the documentation is not in sync with the latest release for webhook implementation.
Also, We found that the document file extension property in envelope create is not in sync with the latest code. The document shows _doc.extension_ while it should be _doc.fileExtension_.

Please let us know what we are doing wrong.

Thanks
Ashutosh

**Comment by acooper4960** [comment] 2019-01-18 21:53
Hi @ashutosh8, you are correct. Those recipes are quite old and haven't been updated in some years.
The issue is setters and getters listed in this example only existed in an older version of the node SDK. 

Please try setting / getting the eventStatus directly as well as other object properties that you need  to access going forward.

**Comment by acooper4960** [comment] 2019-01-25 19:30
Hi @ashutosh8, you are correct these recipes are out of date, and are using a legacy node SDK. The current SDK has had no getter and setter methods for some time now. 

Could you please try to mutate and access the properties of these functions directly as opposed to using these helpers as suggested in this recipe?

**Comment by LarryKlugerDS** [comment] 2019-06-30 17:11
I suggest that you also investigate our most current examples for Connect listeners. They work with AWS, Google Cloud, and Azure to implement an asynchronous, loosely coupled Connect framework that includes easy access to the notification messages from behind the firewall. (With no changes needed to the firewall.)

See 

* https://github.com/docusign/connect-node-listener-aws
* https://github.com/docusign/connect-node-listener-azure
* https://github.com/docusign/connect-node-listener-gcloud

(And each of those repos also links to the matching worker code example.)

**Comment by LarryKlugerDS** [comment] 2019-08-05 07:42
The new AWS / Azure / Google Cloud examples listed in the prior comment are planned to become our recommended code examples for using Connect. I'm closing this issue since the examples are now available on GitHub.

Please add a comment if you feel the issue should be re-opened. Thank you.

**Closed** 2019-08-05 07:43 UTC
Labels: DPE-92, answered, area-docs, has ticket, question
