### ISSUE TITLE
Corporate Proxy Setting

### ISSUE THREAD

**Issue by Bollerd** [docusign/docusign-node-client#135] opened 2019-06-11 12:34 UTC
Currently it is not possible to use the npm module behind a corporate proxy server. Even with setting process.env.http_proxy and process.env.https_proxy the corporate proxy settings, the requests do fail. The same code works outside corporate network. 

Checking the source code it seems from my side, this is coming from the requests that are not done via npm request. Instead some http requests are done with superagent.

Performing some checks with superagent as a helloworld script showed, that superagent will not consider proxy settings. Can you please adopt your code to implement with superagent-proxy that also the superagent code parts are considering the proxy settings.

Thanks

**Comment by acooper4960** [comment] 2019-06-11 19:57
Hi @Bollerd please see https://github.com/docusign/docusign-node-client/issues/71 for the current status of this item.

**Comment by LarryKlugerDS** [comment] 2019-06-30 16:15
This issue is effectively a duplicate of #71. So will close this issue. Please re-open it if you feel the solution or issue is different from #71.

Thank you,
Larry

**Closed by LarryKlugerDS** 2019-06-30 16:15 UTC
Labels: DCM-2979, duplicate
